### ISSUE TITLE
Breakpoint Group does not exist

### ISSUE THREAD

**Issue by danny-englander** [fourkitchens/emulsify#282]
I see in this merged pull request (https://github.com/fourkitchens/emulsify/pull/187) that there's a test step to "_Add a new responsive image style and **select Emulsify** for the breakpoint group_". However, I don't see where there are any groups defined in `emulsify.breakpoints.yml`, thus when I go to add a new responsive image style, there is no evidence of an Emulsify breakpoint group in the UI under /admin/config/media/responsive-image-style/add. Perhaps I am missing something here? Note I have my own generated emulsify theme but to test this, I switched to Emulsify itself to confirm. 

In https://github.com/fourkitchens/emulsify/blob/develop/emulsify.breakpoints.yml, I don't see any [code for a group](https://www.drupal.org/docs/8/theming-drupal-8/working-with-breakpoints-in-drupal-8) which would be something like:

```
yourtheme.group1.mobile:
  label: narrow
  mediaQuery: ''
  weight: 0
  multipliers:
    - 1x
  group: yourtheme.group1
```
