### ISSUE TITLE
typography.com

### ISSUE THREAD

**Issue by StevenDesignCo** [fourkitchens/emulsify#319]
What is the best practice for fonts hosted elsewhere? Like typography.com. For both the theme and Pattern Lab.

**Comment by amazingrando** [comment]
For Emuslify, add the CSS inside of `themeName.libraries.yml` you would add the CSS.

```
global:
  css:
    theme:
      //cloud.typography.com/00000/00000/css/fonts.css: { external: true, minified: true }
```

For Pattern Lab, you can add to `theme/components/_meta/_00-head.twig`, which is the head for all the Pattern Lab pages.
