### ISSUE TITLE
Include scripts-styleguide.js by default in library definitions

### ISSUE THREAD

**Issue by rupl** [fourkitchens/emulsify#68]
I was stuck trying to figure out why I couldn't see a concatenated file that seemed to be generating properly when I realized there are two JS tasks in the gulp file. One is for global JS and that is already defined in `emulsify.libraries.yml` but the other is `scripts-styleguide.js` which concats all the individual components and makes them available to Drupal.

A simple addition to the YML got me up and running:

```yml
  js:
    dist/scripts.js: {}
    dist/scripts-styleguide.js: {}
  dependencies:
    - core/jquery
```
